//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 04:45:48 PM MSK 
//


package ru.basanov.portalad.soap.sale;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.basanov.portalad.soap.sale package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.basanov.portalad.soap.sale
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSaleReqeust }
     * 
     */
    public GetSaleReqeust createGetSaleReqeust() {
        return new GetSaleReqeust();
    }

    /**
     * Create an instance of {@link SaleReqeust }
     * 
     */
    public SaleReqeust createSaleReqeust() {
        return new SaleReqeust();
    }

    /**
     * Create an instance of {@link GetSaleResponse }
     * 
     */
    public GetSaleResponse createGetSaleResponse() {
        return new GetSaleResponse();
    }

    /**
     * Create an instance of {@link SaleResponse }
     * 
     */
    public SaleResponse createSaleResponse() {
        return new SaleResponse();
    }

}
